In [1]:
!pip install numpy

In [2]:
import numpy as np

#### creating a one-dimentional array 

In [3]:
a=np.array([1,4,6,8,9],dtype=np.int32)
print(a)

[1 4 6 8 9]


In [4]:
b=np.array([4,9],int)
print(b)

[4 9]


In [5]:
type(a)

numpy.ndarray

In [6]:
type(b)

numpy.ndarray

#### creating two dimentional array

In [7]:
c=np.array([[1,2,3,4],[5,6,7,8]],int)
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
type(c)

numpy.ndarray

#### Creating ZERO'S array

In [9]:
z=np.zeros(4)
print(z)

[0. 0. 0. 0.]


In [10]:
#Two dimensional array
u=np.zeros((3,3))
print(u)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Creating ONE'S array

In [11]:
o=np.ones(3)
print(o)

[1. 1. 1.]


In [12]:
ot=np.ones((5,5))
print(ot)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### Creating array with random numbers

In [13]:
r=np.random.rand(2,3)
print(r)

[[0.5591875  0.06596208 0.35527953]
 [0.4622604  0.78335514 0.47274746]]


In [14]:
rn=np.random.rand(6,3)
print(rn)

[[0.89769673 0.09320387 0.66112917]
 [0.19113974 0.66640611 0.06228511]
 [0.13342915 0.25032844 0.90978816]
 [0.71266805 0.56997109 0.08278208]
 [0.8167309  0.89835745 0.27611762]
 [0.57161072 0.19298197 0.75166178]]


#### Create An array of particular dimension and particular value


In [15]:
y=np.full((4,4),5.5)
print(y)

[[5.5 5.5 5.5 5.5]
 [5.5 5.5 5.5 5.5]
 [5.5 5.5 5.5 5.5]
 [5.5 5.5 5.5 5.5]]


#### UNIT MATRIX

In [16]:
u=np.eye(4)
print(u)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
u=np.eye(3,k=0)
print(u)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
#Changing diagnal values from one position above
u=np.eye(4,k=1)
print(u)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [19]:
#Changing diagnal values from two positions below
u=np.eye(4,k=-2)
print(u)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


#### Evenly spaced ndarray


In [20]:
e=np.arange(10)
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
e=np.arange(1,20,4)
print(e)

[ 1  5  9 13 17]


In [22]:
e=np.linspace(1,20,10)
print(e)

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


#### SHAPE AND RE-SHAPE

In [23]:
a.ndim

1

In [24]:
c.ndim

2

In [25]:
e.ndim

1

In [26]:
#Shape of NumPy array
a.shape

(5,)

In [27]:
e.shape

(10,)

In [28]:
c.shape

(2, 4)

#### SIze of numpy array

In [29]:
#size=rows*columns
s=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(s)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
s.size

9

#### Reshaping a array

In [31]:
rs=np.array([4,5,6,7,8,9])
np.reshape(rs,(3,2))

array([[4, 5],
       [6, 7],
       [8, 9]])

In [32]:
rs=np.array([4,5,6,7,8,9])
np.reshape(rs,(2,3))

array([[4, 5, 6],
       [7, 8, 9]])

#### Flattening a NumPy array


In [33]:
#Convert into multidimensional to one dimensional using flatten and ravel

"""
1.What is happening here is that flatten() creates a Deep copy of the ndarray while ravel() creates a Shallow copy of the ndarray.
2.Deep copy means that a completely new ndarray is created in memory and the ndarray object returned by flatten() is now pointing to this memory location. 
  Therefore, any changes made here will not be reflected in the original ndarray.
3.A Shallow copy, on the other hand, returns a reference to the original memory location. 
  Meaning the object returned by ravel() is pointing to the same memory location as the original ndarray object
""" 

'\n1.What is happening here is that flatten() creates a Deep copy of the ndarray while ravel() creates a Shallow copy of the ndarray.\n2.Deep copy means that a completely new ndarray is created in memory and the ndarray object returned by flatten() is now pointing to this memory location. \n  Therefore, any changes made here will not be reflected in the original ndarray.\n3.A Shallow copy, on the other hand, returns a reference to the original memory location. \n  Meaning the object returned by ravel() is pointing to the same memory location as the original ndarray object\n'

In [34]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=a.flatten()
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
c=a.ravel()
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
b[0]=0
print(b)
print(a)

[0 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
c[0]=0
print(c)
print(a)

[0 2 3 4 5 6 7 8 9]
[[0 2 3]
 [4 5 6]
 [7 8 9]]


#### Transpose of a NumPy array

In [38]:
a

array([[0, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
t=a.transpose()
t

array([[0, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#### Expanding a NumPy array


In [40]:
a

array([[0, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
a.shape

(3, 3)

In [42]:
e=np.expand_dims(a,axis=1)
print(e)

[[[0 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


In [43]:
e.shape

(3, 1, 3)

In [44]:
f=np.expand_dims(a,axis=0)
print(f)

[[[0 2 3]
  [4 5 6]
  [7 8 9]]]


In [45]:
f.shape

(1, 3, 3)

In [46]:
e

array([[[0, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

#### Squeezing a NumPy array

In [47]:
s=e.squeeze(1)
print(s)

[[0 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
s.shape

(3, 3)

In [49]:
d=e.squeeze()
print(d)

[[0 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
d.shape

(3, 3)

#### Slicing  NumPy arrays

In [51]:
"""Slicing means retrieving elements from one index to another index"""

'Slicing means retrieving elements from one index to another index'

In [52]:
a = np.array([1,2,3,4,5,6])

In [53]:
print(a[1:5:2])

[2 4]


In [54]:
print(a[1:5])

[2 3 4 5]


In [55]:
print(a[:5])

[1 2 3 4 5]


In [56]:
print(a[:-2])

[1 2 3 4]


In [57]:
print(a[:])

[1 2 3 4 5 6]


In [58]:
#Slicing 2-D NumPy arrays
a = np.array([[1,2,3],[4,5,6]])
print(a[0,0])
print(a[1,2])
print(a[1,0])

1
6
4


In [59]:
print(a[0:1,:])

[[1 2 3]]


In [60]:
print(a[1:,:])

[[4 5 6]]


In [61]:
#Slicing 3-D NumPy arrays
a = np.array([[[1,2],[3,4],[5,6]],# first axis array
             [[7,8],[9,10],[11,12]],# second axis array
             [[13,14],[15,16],[17,18]]])

In [62]:
print(a)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [63]:
print(a[0,0,0])

1


In [64]:
print(a[0,:,1])

[2 4 6]


In [65]:
print(a[2,1,:])

[15 16]


In [66]:
a[1:,0:2,0:2]

array([[[ 7,  8],
        [ 9, 10]],

       [[13, 14],
        [15, 16]]])

In [67]:
a[1:,0:2,0:2].flatten()

array([ 7,  8,  9, 10, 13, 14, 15, 16])

#### reverse an ndarray

In [68]:
a


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [69]:
np.flip(a,0)

array([[[13, 14],
        [15, 16],
        [17, 18]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[ 1,  2],
        [ 3,  4],
        [ 5,  6]]])

In [70]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [71]:
"""reversinga total columns"""
np.flip(b,1)

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6]])

In [72]:
"""reversinga total rows"""
np.flip(b,0)

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

#### Stacking ndarrays

In [73]:
a=np.arange(0,5)
b=np.arange(5,10)
print("a is:",a)
print('b is :',b)

a is: [0 1 2 3 4]
b is : [5 6 7 8 9]


In [74]:
vs=np.vstack((a,b))
print(vs)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [75]:
vs.shape

(2, 5)

In [76]:
vs.ndim

2

In [77]:
ba=np.hstack((a,b))
print(ba)

[0 1 2 3 4 5 6 7 8 9]


In [78]:
d=np.dstack((a,b))
d

array([[[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]]])

#### Concatenating ndarrays

In [79]:
a=np.arange(0,5).reshape(1,5)
b=np.arange(5,10).reshape(1,5)
print("a is:",a)
print('b is :',b)

a is: [[0 1 2 3 4]]
b is : [[5 6 7 8 9]]


In [80]:
c=np.concatenate((a,b),axis=0)
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [81]:
c.shape

(2, 5)

In [82]:
c.ndim

2

In [83]:
np.concatenate((a,b),axis=1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [84]:
a.shape

(1, 5)

#### Use of Broad casting

In [85]:
"""Broad casting:The term broadcasting refers to the ability of NumPy to treat arrays of different shapes
       during arithmetic operations"""

'Broad casting:The term broadcasting refers to the ability of NumPy to treat arrays of different shapes\n       during arithmetic operations'

In [106]:
a = np.arange(10,20,2)
b = np.array([[2,3],[3,2]])
print(a)
print(b)
print(np.shape(a))
print(np.shape(b))
c=a+b
d=a*2
print('Adding two different size arrays :','\n',c)
print('Multiplying an ndarray and a number :',d)
print(np.shape(c))
print(np.shape(d))


[10 12 14 16 18]
[[2 3]
 [3 2]]
(5,)
(2, 2)


ValueError: operands could not be broadcast together with shapes (5,) (2,2) 

In [112]:
'''1.Both have the same dimensions
   2.Either of the ndarrays has a dimension of 1. 
     The one having a dimension of 1 is broadcast to meet the size requirements of the larger ndarray'''

'1.Both have the same dimensions\n   2.Either of the ndarrays has a dimension of 1. \n     The one having a dimension of 1 is broadcast to meet the size requirements of the larger ndarray'

In [105]:
e=np.reshape(b,(4,1))

In [111]:
a = np.arange(10,20,2)
b = np.array([[2,3],[3,2]])
print(a)
print(b)
print('shape of a is:',np.shape(a))
print('shape of b is:',np.shape(b))
b=np.reshape(b,(4,1))
c=a+b
d=a*2
print('Adding two different size arrays :','\n',c)
print('Multiplying an ndarray and a number :',d)
print('shape of a is:',np.shape(a))
print('shape of b is:',np.shape(b))
print('shape of c is:',np.shape(c))
print('shape of d is:',np.shape(d))


[10 12 14 16 18]
[[2 3]
 [3 2]]
shape of a is: (5,)
shape of b is: (2, 2)
Adding two different size arrays : 
 [[12 14 16 18 20]
 [13 15 17 19 21]
 [13 15 17 19 21]
 [12 14 16 18 20]]
Multiplying an ndarray and a number : [20 24 28 32 36]
shape of a is: (5,)
shape of b is: (4, 1)
shape of c is: (4, 5)
shape of d is: (5,)


#### NumPy Ufuncs(Universal Functions)
This problem manifests itself when Python has to do many operations repeatedly, like the addition of two arrays. This is so because each time an operation needs to be performed, Python has to check the data type of the element. This problem is overcome by NumPy using the ufuncs function.

The way NumPy makes this work faster is by using vectorization. Vectorization performs the same operation on ndarray in an element-by-element fashion in a compiled code. So the data types of the elements do not need to be determined every time, thereby performing faster operations.


In [119]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
%timeit a+b

542 ns ± 8.98 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### Maths with NumPy arrays


#### 1.Basic arithmetic operations on NumPy arrays

In [121]:
print('addition is:',a+b)
print('subtraction is:',a-b)
print('multiplication is:',a*b)
print('devision is:',a/2)

addition is: [ 7  9 11 13 15]
subtraction is: [-5 -5 -5 -5 -5]
multiplication is: [ 6 14 24 36 50]
devision is: [0.5 1.  1.5 2.  2.5]


#### 2.Mean, Median and Standard deviation

In [122]:
print('Mean is:',np.mean(a))
print('Median is:',np.median(a))
print("sd is :",np.std(a))

Mean is: 3.0
Median is: 3.0
sd is : 1.4142135623730951


#### 3.Min-Max values and their indexes

In [123]:
a = np.array([[1,6],
[4,3]])

In [127]:
a

array([[1, 6],
       [4, 3]])

In [125]:
print('min is:',np.min(a))#min value total array
print('min is:',np.min(a,axis=0))#min value along row-wise
print('min is:',np.min(a,axis=1))#min value along column-wise

min is: 1
min is: [1 3]
min is: [1 3]


In [126]:
print('max is:',np.max(a))
print('max is:',np.max(a,axis=0))
print('max is:',np.max(a,axis=1))

min is: 6
min is: [4 6]
min is: [6 4]


#### 4.Sorting in NumPy arrays

In [128]:
a = np.array([1,4,2,5,3,6,8,7,9])

In [130]:
%timeit np.sort(a, kind='quicksort')

2.54 µs ± 170 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [131]:
%timeit np.sort(a, kind='mergesort')

2.57 µs ± 101 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [132]:
%timeit np.sort(a, kind='heapsort')

2.53 µs ± 131 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [133]:
%timeit np.sort(a, kind='stable')

2.47 µs ± 183 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### NumPy arrays and Images

In [139]:
import numpy as np
!pip install Pillow

In [140]:
from PIL import Image
image = Image.open('johny depp.jfif')

In [141]:
print(image.format)
print(image.size)
print(image.mode)

JPEG
(130, 130)
RGB


In [143]:
from numpy import asarray

In [146]:
numpydata = asarray(image)

In [147]:
print(numpydata)

[[[ 34  27  21]
  [ 23  16  10]
  [ 16   9   3]
  ...
  [ 14   5  10]
  [ 11   2   3]
  [ 11   2   3]]

 [[ 34  27  21]
  [ 24  17  11]
  [ 17  10   4]
  ...
  [ 14   5  10]
  [ 12   3   4]
  [ 12   3   4]]

 [[ 35  28  22]
  [ 24  17  11]
  [ 18  11   5]
  ...
  [ 15   6   9]
  [ 14   5   6]
  [ 14   5   6]]

 ...

 [[ 29  24  20]
  [ 26  22  19]
  [ 30  26  23]
  ...
  [  6   6   8]
  [ 11   7  30]
  [ 81  77 100]]

 [[ 30  25  21]
  [ 31  26  22]
  [ 31  26  22]
  ...
  [  1   0   8]
  [ 38  35  64]
  [ 81  78 107]]

 [[ 30  25  21]
  [ 31  26  22]
  [ 31  26  22]
  ...
  [  1   0   8]
  [ 43  40  69]
  [ 85  82 111]]]


# -----------------------------------------------------END----------------------------------------------------